aspell: fix PKGBUILD
function CHECK:
- fix variable
- remove make flag '-k'
- remove .sig file from sources since public key unknown
  ERROR: aspell-0.60.8.tar.gz ... FAILED (unknown public key B6D9D0CC38B327D7)